Config = {}

Config.BanditsPerRaid = 2
Config.WaitTimeBetweenPoints = 60000 -- 1 minute
Config.AggressionRange = 30.0 -- or whatever range you want, in game units
Config.BanditAccuracy = 100 -- for example, setting bandit accuracy to 75%
Config.RaidPaths = {
    {
        spawnPoint = vector3(-174.93, 997.54, 145.37),
        path = {
            ---vector3(-331.15, 784.70, 116.15),---val
            ---vector3(-801.24, -1305.81, 43.49),---blackwater
            vector3(2523.78, -1312.87, 49.02),---stdenis
        }
    },
    -- Add more raid paths as needed
}

Config.Weapons = {
    0x772C8DD6, 
	0x169F59F7, 
	0xDB21AC8C, 
	0x6DFA071B,
    0xF5175BA1, 
	0xD2718D48, 
	0x797FBF5, 
	0x772C8DD6,
    0x7BBD1FF6, 
	0x63F46DE6, 
	0xA84762EC, 
	0xDDF7BC1E,
    0x20D13FF, 
	0x1765A8F8, 
	0x657065D6, 
	0x8580C63E,
    0x95B24592, 
	0x31B7B9FE, 
	0x88A855C, 
	0x1C02870C,
    0x28950C71, 
	0x6DFA071B
}

Config.HorseModels = {
	"A_C_HORSE_GANG_KIERAN",
	"A_C_HORSE_MORGAN_BAY",
	"A_C_HORSE_MORGAN_BAYROAN",
	"A_C_HORSE_MORGAN_FLAXENCHESTNUT",
	"A_C_HORSE_MORGAN_PALOMINO",
	"A_C_HORSE_KENTUCKYSADDLE_BLACK",
	"A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO",
	"A_C_HORSE_KENTUCKYSADDLE_GREY",
	"A_C_HORSE_KENTUCKYSADDLE_SILVERBAY",
	"A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO",
	"A_C_HORSE_TENNESSEEWALKER_CHESTNUT",
	"A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY",
	"A_C_HORSE_TENNESSEEWALKER_REDROAN",
	"A_C_HORSE_AMERICANPAINT_GREYOVERO",
	"A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE",
	"A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN",
	"A_C_HORSE_ANDALUSIAN_DARKBAY",
	"A_C_HORSE_ANDALUSIAN_ROSEGRAY",
	"A_C_HORSE_APPALOOSA_BROWNLEOPARD",
	"A_C_HORSE_APPALOOSA_LEOPARD",
	"A_C_HORSE_ARABIAN_BLACK",
	"A_C_HORSE_ARABIAN_ROSEGREYBAY",
	"A_C_HORSE_ARDENNES_BAYROAN",
	"A_C_HORSE_ARDENNES_STRAWBERRYROAN",
	"A_C_HORSE_BELGIAN_BLONDCHESTNUT",
	"A_C_HORSE_BELGIAN_MEALYCHESTNUT",
	"A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN",
	"A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN",
	"A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN",
	"A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY",
	"A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO",
	"A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE",
	"A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO",
	"A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN",
	"A_C_HORSE_SHIRE_DARKBAY",
	"A_C_HORSE_SHIRE_LIGHTGREY",
	"A_C_HORSE_SUFFOLKPUNCH_SORREL",
	"A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT",
	"A_C_HORSE_TENNESSEEWALKER_FLAXENROAN",
	"A_C_HORSE_THOROUGHBRED_BRINDLE",
	"A_C_HORSE_TURKOMAN_DARKBAY",
	"A_C_HORSE_TURKOMAN_GOLD",
	"A_C_HORSE_TURKOMAN_SILVER",
	"A_C_HORSE_GANG_BILL",
	"A_C_HORSE_GANG_CHARLES",
	"A_C_HORSE_GANG_DUTCH",
	"A_C_HORSE_GANG_HOSEA",
	"A_C_HORSE_GANG_JAVIER",
	"A_C_HORSE_GANG_JOHN",
	"A_C_HORSE_GANG_KAREN",
	"A_C_HORSE_GANG_LENNY",
	"A_C_HORSE_GANG_MICAH",
	"A_C_HORSE_GANG_SADIE",
	"A_C_HORSE_GANG_SEAN",
	"A_C_HORSE_GANG_TRELAWNEY",
	"A_C_HORSE_GANG_UNCLE",
	"A_C_HORSE_GANG_SADIE_ENDLESSSUMMER",
	"A_C_HORSE_GANG_CHARLES_ENDLESSSUMMER",
	"A_C_HORSE_GANG_UNCLE_ENDLESSSUMMER",
	"A_C_HORSE_AMERICANPAINT_OVERO",
	"A_C_HORSE_AMERICANPAINT_TOBIANO",
	"A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE",
	"A_C_HORSE_AMERICANSTANDARDBRED_BLACK",
	"A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN",
	"A_C_HORSE_APPALOOSA_BLANKET",
	"A_C_HORSE_APPALOOSA_LEOPARDBLANKET",
	"A_C_HORSE_ARABIAN_WHITE",
	"A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT",
	"A_C_HORSE_MUSTANG_GRULLODUN",
	"A_C_HORSE_MUSTANG_WILDBAY",
	"A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY",
	"A_C_HORSE_NOKOTA_BLUEROAN",
	"A_C_HORSE_NOKOTA_WHITEROAN",
	"A_C_HORSE_THOROUGHBRED_BLOODBAY",
	"A_C_HORSE_THOROUGHBRED_DAPPLEGREY",
	"A_C_Donkey_01",
}

Config.BanditsModel = {
	"G_M_M_UniBanditos_01",
	"A_M_M_GRIFANCYDRIVERS_01",
	"A_M_M_NEAROUGHTRAVELLERS_01",
	"A_M_M_RANCHERTRAVELERS_COOL_01",
	"A_M_M_RANCHERTRAVELERS_WARM_01",
}

